Repository K5S-TEAM/gitTest, pull requests merged in 2022-04, with the labels that each got.

#2 [#1] - Member Domain 개발
  chan/RepositoryFILE
  chan/ServiceFILE
  chan/ServiceTestFILE
Labels: enhancement

#7 Issue TEST
  chans/TEST
Labels: bug

#9 vpc image 추가
  vpc/terraform_aws_architecture_diagram.png
Labels: documentation
